technologies = Technology.
           create!([
                     'Angular',
                     'ASP.NET',
                     'Backbone.js',
                     'Bash',
                     'C',
                     'C#',
                     'C++',
                     'CakePHP',
                     'Cassandra',
                     'Clojure',
                     'CodeIgniter',
                     'CoffeeScript',
                     'CSS',
                     'CVS',
                     'D',
                     'Dart',
                     'Django',
                     'Docker',
                     'Elasticsearch',
                     'Elixir',
                     'Ember.js',
                     'Erlang',
                     'Express',
                     'F#',
                     'Flask',
                     'Git',
                     'Go',
                     'Grails',
                     'Haskell',
                     'HTML',
                     'Java',
                     'JavaScript',
                     'jQuery',
                     'JSF',
                     'Kotlin',
                     'Kubernetes',
                     'Laravel',
                     'Less',
                     'Lisp',
                     'Lua',
                     'Microsoft SQL Server',
                     'MongoDB',
                     'MySQL',
                     'Objective-C',
                     'Oracle',
                     'Perl',
                     'Phoenix',
                     'PHP',
                     'Play',
                     'PostgreSQL',
                     'Python',
                     'R',
                     'React Native',
                     'React',
                     'Redis',
                     'Ruby on Rails',
                     'Ruby',
                     'Rust',
                     'Sass',
                     'Scala',
                     'Sinatra',
                     'Spring',
                     'SQLite',
                     'Stimulus',
                     'Struts',
                     'SVN',
                     'Swift',
                     'Symfony',
                     'Tailwind CSS',
                     'TypeScript',
                     'Vaadin',
                     'Vue.js',
                     'Webpack',
                   ].map { |technology| {name: technology} }).
           map { |technology| [technology.name.parameterize(separator: '_').to_sym, technology] }.
           to_h

company = Company.create! name: 'Example Inc'
role_description = RoleDescription.create! name: 'Full stack software engineer', company: company, technologies: technologies.slice(:ruby, :css, :html, :postgresql).values

interviewee = Interviewee.create! name: 'John Doe', email: 'john.doe@example.com'
job_application = JobApplication.create! role_description: role_description, interviewee: interviewee
self_evaluation = SelfEvaluation.create! job_application: job_application, slug: SecureRandom.hex
